name: tflite
description: A Flutter plugin for accessing TensorFlow Lite. Supports both iOS and Android.
version: 1.1.2
homepage: https://github.com/shaqian/flutter_tflite

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5



# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: sq.flutter.tflite
        pluginClass: TflitePlugin
      ios:
        pluginClass: TflitePlugin
